### ISSUE TITLE
Invisible mask areas are generated in Zbrush when exported from Blender to Zbrush if a mesh had mask areas before

### ISSUE THREAD

**Issue by Tsukasa-YAMATO** [JoseConseco/GoB#105]
environment
Windows 10 Pro
Blender 2.83
GoB 3.3.8 ( published as “FaceMapsExport”)
https://github.com/JoseConseco/GoB/issues/103#issuecomment-642157397
Zbrush 2020.1.4
(Preferences settings remain the default values of Ver.3.3.8)

-------

This issue is related to the following bugs: It was a bug in Ver.3.3.7, but it was also found in Ver.3.3.8.

https://github.com/JoseConseco/GoB/issues/99#issuecomment-640015130

The details of the bug and the reproduction procedure are as follows.

https://github.com/JoseConseco/GoB/issues/99#issuecomment-640023721

After masking with Zbrush once and sending to Blender with GoB, I cleared the mask with CTRL + left drag on background area of Zbrush. Then I exported the mesh from Blender to Zbrush with GoB, the mask was not be visible on Zbrush. However, the mask area has been regenerated and acts as a mask.

![2020-06-06_18h35_07](https://user-images.githubusercontent.com/65609416/83941210-94fb2f00-a824-11ea-8373-d3696dd1615d.jpg)

Invisible mask areas are very annoying because they interfere with accurate work, and it causes unintended deformation.

Did you forget to implement the mask clear-off function?
As for how to deal with the mask area, I remember that you are going to plan to forcibly clear the mask and load it into Zbrush  as a provisional measure. Is this correct?

I post this issue as a new issue so that you can manage this easier on task lists for you.

Please check the code on GoB.

**Comment by kromar** [comment]
Aha i did misunderstand this the first time you described it, now its clear what you maen.
No i did not implement this but thought it was related to another bug where a hidden checkerboard mask is sent to zbrush. that one should be fixed.

![Screen Shot 05-24-20 at 11 52 PM](https://user-images.githubusercontent.com/1472884/84425052-41705300-ac21-11ea-940c-c45c1282fcc9.PNG)

As for this current issue, i think this should be resolved when the mask import and export is configurable as far as i understand (correct me if im wrong on that). 
This would allow you to send the mask from zbrush to blender but not the other way around or not at all.
That is something i want to tackle in the next release.

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
Whether there had been  a mask on the Zbrush mesh or not, it is enough if the mask area is cleared when returning from Blender to Zbrush.

That is a request from many creators. :)
(Almost all creaters never want  to recover previous mask area recovering but they wants a cleared mask mesh.)

**Comment by kromar** [comment]
@Tsukasa-YAMATO i tried to not export the mask from blender but it seems i can not do that without clearing the mask in zbrush.
I tested a couple scenarios and if the mask "vertex group" is not present or i do not export the mask from blender the **mask in zbrush is cleared**.

I think we are on a limitation of what the transfer can do, i am not able to make something that does not clear the mask if zbrush if it has one. My proposal is to have a option that is called "Clear Mask" in the export that will not transfer the current mask information from blender and will clear the mask in zbrush since that seems to be what it does.

![image](https://user-images.githubusercontent.com/1472884/84826117-c47b1a00-b022-11ea-8620-59982882792c.png)

Here is a version so you can try it and already did the renaming. Not sure if that option is better than what we have currently but i think its the best that is possible for this problem.
https://github.com/kromar/blender_GoB/tree/feature/clear_mask

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
Thank you for a new implementation.

I have tested it. Very good implementation.
At least this is no problem because the "invisible mask" caused by GoB transfer is no longer present. Also, if users need a mask, they can turn off the "clear mask" and operate it, so I think it is an implementation that satisfies all users.

**Comment by kromar** [comment]
great to hear that you like it:D so i will bring this back then and create a release version!

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
Congratulations on the stable release of GoB Ver3.3.8! And thank you for writing my name in the release notes. I am very happy.
Now I can finally introduce the stable version of Ver.3.3.8 to many friends.

(In addition, I have also tested Ver.3.3.9 beta version. It is a version with an "mask " item added to import settings. Currently, for users who do not use mask, there wiil be no difference between Ver.3.3.9 and  Ver.3.3.8 stable version. However, it is very good that the user can turn ON/OFF the items that are necessary/unnecessary for the user itself.)
