### ISSUE TITLE
create material for texture import

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#112]
**v3.4.1**
https://github.com/kromar/blender_GoB/tree/feature/texture_node

![image](https://user-images.githubusercontent.com/1472884/85928632-bba20800-b8ae-11ea-828e-8e0e7fe405e6.png)
![image](https://user-images.githubusercontent.com/1472884/85928572-46363780-b8ae-11ea-9120-0393bcbd8c01.png)
![image](https://user-images.githubusercontent.com/1472884/85928553-1e46d400-b8ae-11ea-814e-41fb740d3c1b.png)

**Comment by kromar** [comment]
@Tsukasa-YAMATO i restored the texture import to how it was working for blender 2.79 and was broken due to the move to node setups. 
The textures from zbrush will now like the Vertex Color create nodes for the specific textures that are sent over.
This is only possible from zbrush to blender and not in the other direction due to some limitations on GoZ.

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
Thanks for your comment. But I could hardly understand.
I have absolutely no expectations for textures in Zbrush. Zbrush and texture are too bad friends. My expectations for GoB are up to modeling, polypaint is just an extra option, and I'm totally indifferent to textures. I do it on Blender, not on Zbrush.

And I'm also not interested in Blender 2.79.

I think you can act on this matter at your discretion. There are few things I can comment because I don't really understand about this issue.
I'm very sorry.

**Comment by kromar** [comment]
Alright, take it as information in that case that its available;D
