### ISSUE TITLE
crash when applying face maps to face sets

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#113]
Activated the option in ZBrush prefs, but now Blender crashes each time I try to GoZ all from ZBrush to Blender. I’m using the latest 2.9 alpha build.

Tested some more…

Blender only crashes if you send something you created from scratch in ZBrush (with Import as Subtools activated) to an empty Blender.

Blender doesn’t crash if you send a scene from Blender to ZBrush first, but when I do some deformations and send the subtools back, the position of the objects is not correct anymore in Blender:

![image](https://user-images.githubusercontent.com/1472884/85221850-8df12680-b3b7-11ea-919f-daef184ddc0f.png)

**Comment by kromar** [comment]
@Tsukasa-YAMATO a crash was reported when "apply face maps to face sets" is enabled (which it is by default) and GoZ all in zbrush is used.
I recommend disabling this until i found a solution to fix the crash.

![ad1dcb6f826076bd99ddb1dc63282d2e22c38808](https://user-images.githubusercontent.com/1472884/85228891-9b71d500-b3e6-11ea-8949-2f3f528da147.png)

![ddc1b09bf500cf8cafc356a5306eb95297cbf87f_2_1035x700](https://user-images.githubusercontent.com/1472884/85228835-39b16b00-b3e6-11ea-9834-0253f7b53e41.png)

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
Japan is late at night, so my head doesn't work well.
By the way I do not recommend verifying the operation on the alpha version. The alpha version changes every day by day, and many users are most interested in "What about the stable version Ver.2.83 (LTS)?"
I'll test it when I have enough time, but it's on 2.83. It is not an alpha version.

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
GoB Ver.3.3.9
Blender 2.83

Blender didn't crash on GoZ All in this environment, but the ability to transfer to Face Sets was barely functional.
But if I transfer them one by one, it works.
Many of my friends (3DCG creators) want one subtool transfer of "reliable round trip to Blender and Zbrush" rather than a bulk transfer. Because Zbrush's mesh can have so massive polygons that it increases the risk of crashes, and 3DCG creaters are most afraid of the crashes.
So I think neither my friends nor I use the All button. So I don't think it will be a practical use problem.
Of course, it's good to fix bugs in order to improve the stability of GoB add-ons.

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
I think that it is different from the "All button problem" but it is very likely related to the misaligned problem, so please take a look.

https://github.com/JoseConseco/GoB/issues/119

**Comment by kromar** [comment]
@Tsukasa-YAMATO of course its important to reproduce the crash on the release version, i usually test on both versions to see if there are unexpected things happening. And recently i got those crashes on one system with 2.83 and not on my other one but it seems i was just doing something different. i was able to reproduce the crash consistently on 2.83 as well and that should never happen. However since its something i also do not often use it seemed to have slipped by the release.

I think i will disable this for now and wait for the proper face sets exposure so i do not need to do this hack in the addon and if a user wants his face maps as face sets he can always do it manually.
I will look into the multi object transfer since it should work the same way as when we transfer a single object and all the information should be sent the same way. maybe there is something that im not aware of that is happening when multiple files are transferred. 

I also noticed some other issues with transferring multiple objects but i think its a problem on pixologic's side and i will have to open a bug report on their side to see what they say about it.

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
I think it's better not to go too deep into multi-transfer now. The reason is as follows.

1. GoZ function itself has not been updated from Ver.1.01 (last updated on April 11, 2011)
2. Pixologic is unlikely to focus on GoZ
3. GoB is an unofficial add-on, so Pixologic will not make an effort unless they feel an powerful merit for GoB, I guess.
4. And in the first place, I feel that GoZ's multi-transfer operation is unstable.
5. As I said before, Zbrush's mesh is a very high density polygon, so there is a risk that PC or software will hang during batch transfer. The 3DCG creator is so afraid of it. (They would dare to choose one by one transfer for the safety.)


The more reliable one by one transfer is on GoB, the more valuable GoB is, so I think it should be the first priority. I think multi transfer may be the second priority. 

I strongly feel that it is better not to go deep into multi-transfer.
(Of course, Mr. Daniel's decision should be given the highest priority. This comment is just one of the GoB user's voice.)

----

By the way, I will use GoB with turning off the check box that you pointed out. Because I'm not depending on the Face Sets function at all for now.

**Comment by kromar** [comment]
Haha reminds me of the last time i asked something about goz, never got an answer:D then again ita always worth a try, i had some good communicatiin with the pixologic team on other higs i reported in zbrush so i know they are intrested to make their product more stable.

I agree with you, most users will probably send only one object. However crashes need to be avoided even if its not a nr1 priority to send all over.

And then im also curious to know whats going on there since it should do the same like single transfer:D

**Comment by Tsukasa-YAMATO** [comment]
According to the information, in Zbrush 2020.1.4, the official add-on for "GoZ for 3ds Max" does not work and is causing a problem.
So the Pixologic team will be busy doing that. And the announcement of the revised release is undecided. I don't know whether the team really values ​​GoZ.

https://www.zbrushcentral.com/t/goz-not-installing-in-3ds-max-2021/365876/4

It seems that they will respond to users individually for the time being. This is the current situation regarding GoZ. I have little hope for unofficial add-on's support for a while, I guess . :(

**Comment by kromar** [comment]
to me that looks like they are busy fixing issues, maybe the one i encountered is also included there. Yeah it will be a while until we see a release with those fixes so i better file my report now so they have a chance to get it in if they want to.
