### ISSUE TITLE
review new import

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#137]
the GoZ standard import is bypassed by a custom ZScript, this should fix all the mess the import created with tools an subtools and also brings texture import to the table.

The source and the complied script can be found int a new ZScript subfolder of the addon.

**Comment by kromar** [comment]
@Tsukasa-YAMATO as the ticket describes i have written the bypass of the default GoZ scripts to fix the import issues with tools and subtools and extended it for texture transfer from blender to zbrush.

It would be great if you could test this first version and let me know if you encounter any problems.
If you have a MacOS, i was not able to test this since i do not have a system with that OS running, this might cause some issues so let me know if you do get some.

should be v3_4_4
https://github.com/kromar/blender_GoB/tree/v3_4_4-goz_import_bypass

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
thank you for your comment. But I'm not be able likely to help you. I was pursuing the purely modeling benefits of working with Zbrush and Blender.

The issues like "look" like texturing and rendering are for me the stages where Zbrush is no longer relevant. So I'm not interested in texture coordination between Zbrush and Blender. So don't expect a reply. Maybe I'm not able to test the beta versions for a while for some personal reasons.

And in the first place, I do not understand the current problems. The reason is that, as mentioned above, whether or not there is a problem does not affect the modeling itself, so it is not a concern for me.


I apologize for not being able to cooperate with the test. I hope that a supportive another person will appear.

**Comment by kromar** [comment]
alright i guess i find someone else then. take care
