### ISSUE TITLE
error with object with missing material or empty material

### ISSUE THREAD

**Issue by SbstnDC** [JoseConseco/GoB#154]
![image](https://user-images.githubusercontent.com/22725270/90200132-07652e00-ddd7-11ea-9f42-9adb8a30ec65.png)
when you export an item with missing material from other user, or when you not have a material.
, and you want send to zbrush from blender.

**Comment by kromar** [comment]
@SbstnDC  thanks for reporting the issue, this should already be fixed (https://github.com/JoseConseco/GoB/issues/136)  however is not yet in a release. 
You can either wait for the next release or try the latest version i am working on (you might get other errors due to a lot of changes) 
https://github.com/kromar/blender_GoB/tree/feature/change-execution

**Comment by SbstnDC** [comment]
i see, thanks mate!
