### ISSUE TITLE
import error on MacOS

### ISSUE THREAD

**Issue by 19930227** [JoseConseco/GoB#162]
Hello, I don't know this is an error or my mistake but I have a trouble now.
I tried to import the add-on and when I click the check box this pop up appeared.
https://d.kuku.lu/8b1d37d76e
Could you tell me how can I deal with this?
I'm using Blender 2.83.5 and Zbrush 2021.

Thank you!

**Comment by kromar** [comment]
thanks for reporting this issue, this seems to be a MacOS related issue, since i do not have a system with that OS i cant really reproduce it but i should get a system this week and hope i can fix it.
Please use the latest release until this issue is resolved. 
https://github.com/JoseConseco/GoB/releases

**Comment by kromar** [comment]
i reversed the check on what os is running maybe you can give it a try and see if you get further.
https://github.com/kromar/blender_GoB/tree/bugfix/filter-for-zbrush-executable

however i expect there to be more issues since this version is untested on macos.
