### ISSUE TITLE
Unable to export Blender > ZBrush

### ISSUE THREAD

**Issue by SockGardener** [JoseConseco/GoB#166]
I'm using Blender 2.9 (and 2.91) & ZBrush 2021.1.1 – both on macOS X (Mojave)
Transfer from ZBrush to Blender works really well, however, when exporting from Blender to ZBrush a second instance of ZBrush is launched which promptly crashes with the following error message:

![image](https://user-images.githubusercontent.com/54185922/93116921-e33a8c80-f6b5-11ea-8d1d-a5be6756d8a5.png)

It's certainly possible that this is user error. Have I set the file paths incorrectly?

![image](https://user-images.githubusercontent.com/54185922/93117106-37de0780-f6b6-11ea-8034-c67389bccfd5.png)

ps. thanks for the great addon :)

**Comment by kromar** [comment]
thanks for reporting the issue, there is another report where i asked for more information how to fix the issue
https://www.zbrushcentral.com/t/gob-an-unofficial-goz-for-blender/205495/436
would be great if you could help providing information so i can get this issue fixed. Since i do not have a system with OSX available i can not test this myself.

**Comment by difanxu** [comment]
Hi! i encountered the same problem on MacOS, import from zbrush is totally ok but cannot export from blender to zbrush. My Zbrush configure is set identical as SockGardener. Seems like its where zbrush.app is located bc zbrush booted when i hit export but it gave me the same error warning

**Comment by kromar** [comment]
please give this new version a try and let me know if you got any issues

v3.4.9
https://github.com/kromar/blender_GoB/tree/bugfix/fixmacos

**Comment by difanxu** [comment]
Thank you so much for the update! it works well for me!
