### ISSUE TITLE
Im having issues exporting

### ISSUE THREAD

**Issue by BossTony** [JoseConseco/GoB#173]
I believe I installed everything correctly but when I try to export I get this error every time 

https://gyazo.com/29b54c8c010e03c0795d55febe5e2c5f

but when I check the folders I can see the files being created in C:\Users\Public\Pixologic\GoZProjects\Default
but its just opening over  to ZBrush for some reason

**Comment by kromar** [comment]
the problem with this error is that the zbrush.exe/app input is wrong.  I got a few reports where the executable was missing from the path so make sure its the correct path.
![image](https://user-images.githubusercontent.com/1472884/96642630-b3bb1780-1326-11eb-9f6c-8c36cdb87d1b.png)


also make sure you are using the latest version since there have been a couple of fixes to avoid the error.
https://github.com/JoseConseco/GoB/archive/master.zip
