### ISSUE TITLE
GOB export texture issue 

### ISSUE THREAD

**Issue by Sterling177** [JoseConseco/GoB#218]
![image](https://user-images.githubusercontent.com/61482425/109907940-1a960780-7cef-11eb-9c39-bfcff4762565.png)

Not sure why but the texture from zbrush is all messed up - seems the point order is changed on export

**Comment by kromar** [comment]
what versions of blender, zbrush and GoB do you use?

**Comment by Sterling177** [comment]
Just creating Uv's with UVmaster in zbrush and the using Goz and import with Gob - I understand that Gob is exporting via goz as .obj - none of the textures or shaders are building in Blender either is the texture that is present in the goz folder. 

blender 2.91.2

**Comment by kromar** [comment]
this seems to work fine for me, so im not sure what the problem is on your side. 
have you changed the material import from the default "from polygroup" to "**from texture**"? 

![image](https://user-images.githubusercontent.com/1472884/109990707-f136a500-7d09-11eb-9ca2-638d88edc7e4.png)
![image](https://user-images.githubusercontent.com/1472884/109990885-1c20f900-7d0a-11eb-952f-41d23c001820.png)
![image](https://user-images.githubusercontent.com/1472884/109991016-39ee5e00-7d0a-11eb-9298-20858e9b25a1.png)

**Comment by kromar** [comment]
@Sterling177 bumping this report
