### ISSUE TITLE
error when using apply all modifiers

### ISSUE THREAD

**Issue by Againsttimecosplay** [JoseConseco/GoB#233]
![image](https://user-images.githubusercontent.com/82961691/115584439-5f0c4f80-a2fd-11eb-8876-27a46eb60664.png)

**Comment by Againsttimecosplay** [comment]
the function of goz is available ，I can import from zb to blender

**Comment by kromar** [comment]
thanks for reporting the issue, i already got a report on this but did not have the time yet to fix it, please choose a different way the modifiers are exported until i get the chance to fix the issue.

you can change it in the addon preferences, and only export should work and you will need to apply the modifiers manually until the fix is in.
![image](https://user-images.githubusercontent.com/1472884/115624006-477f9780-a2fa-11eb-94e6-b0cd2f75a08b.png)

**Comment by Againsttimecosplay** [comment]
> thanks for reporting the issue, i already got a report on this but did not have the time yet to fix it, please choose a different way the modifiers are exported until i get the chance to fix the issue.
> 
> you can change it in the addon preferences, and only export should work and you will need to apply the modifiers manually until the fix is in.
> ![image](https://user-images.githubusercontent.com/1472884/115624006-477f9780-a2fa-11eb-94e6-b0cd2f75a08b.png)

thank you very much 
and I found that the lower version addon of Gob master was normal

**Comment by kromar** [comment]
i made a fix for applying the modifiers, would be great if you could give it a try

v3.5.51
https://github.com/kromar/blender_GoB/tree/bugfix/apply-modifiers
