### ISSUE TITLE
ZBrush.2021.6.2 export error to blender.

### ISSUE THREAD

**Issue by SamiMertDemir** [JoseConseco/GoB#234]
This weird issue driving me nuts.I can export models from blender to zbrush but can't from zbrush to blender.I mean model exports to blender but zbrush crashes with this error.Can you provide an answer please?
![Ekran görüntüsü 2021-04-21 223506](https://user-images.githubusercontent.com/82974052/115610659-d805aa00-a2f1-11eb-9fea-698682e6ae5d.jpg)

**Comment by kromar** [comment]
now that is a strange one and most likely not caused by this addon since there is no modification on the export on zbrush. 
Have you tried to run the GoZ installer? you should be able to run it from the GoB addon preferences:
![image](https://user-images.githubusercontent.com/1472884/115624278-b0670f80-a2fa-11eb-9119-ff8f5b5b3bd6.png)

and if that does not work i would try to run the zbrush installer again, maybe something went wrong or is missing from the installation.
If that does not help i would suggest you contact the pixologic support as mentioned in the message since there is nothing i can do to fix anything on the zbrush export side.

**Comment by SamiMertDemir** [comment]
Thank you for your answer.Problem was caused by Zbrush.When I updated the Zbrush that crashing went away.Sorry for the inconvenience.

**Comment by kromar** [comment]
not an inconvenience at all, im glad you got it working. let me know if you run into any other issues.
