### ISSUE TITLE
No export from ZBrush 2021.6.4 to Blender 2.92?

### ISSUE THREAD

**Issue by lensman888** [JoseConseco/GoB#237]
[RESOLVED: Must have been some sort of stupid user error   :) ]

First time install.

Import/Export Buttons appear in Blender. 
I have created a path to Blender in ZBrush GoZ.

I can export from Blender to Zbrush.

But I CANNOT export from Zbrush to Blender. If I click on GoZ a message flashes that file was saved to disk. [<Disregard this - It might have simply been Quicksave saving at the same time]. Then nothing.
If I go into Blender there is nothing there (supposed to automatically import, right?). If I click on Import the button changes colour and that's it. 

Are there any known issues with these latest versions of the programmes?

**Comment by kromar** [comment]
Hi, i assume you did not toggle the import button to the orange "active" state before sending something from zbrush? i was wondering when someone would trip over this logic since it does not seem very intuitive^^
Im glad you got it running. btw you can also use it to send objects to other (maybe multiple) blender instances

**Comment by lensman888** [comment]
Haha. That's exactly what I did.  :)
