### ISSUE TITLE
another size issue

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#246]
when i trying to reexport the object few times i got this result
Zbrush => Blender => Zbrush => Blender [https://prnt.sc/16fcegh](https://prnt.sc/16fcegh)

Blender => Zbrush [https://prnt.sc/16fcuom](https://prnt.sc/16fcuom)

also i tried use manual size in the addon settings but its not work anyway

I remember you had fixed that problem in beta for me and it works perfectly XD

**Comment by koloved** [comment]
i found right scale factor in addon settings = 1000
but it definitely not work properly when you export the same object back to zbrush

**Comment by kromar** [comment]
what scale option did you use when you get the scale issue? Blender Units?

**Comment by kromar** [comment]
the problem is that you change scale with the Scale Master plugin which puts the brushes into some arbitrary scale in zbrush that i have no information of when you send it to blender.

You should just use the geometry size of a mesh that should always correlate to the blender units.
![image](https://user-images.githubusercontent.com/1472884/123525153-02e3f400-d6cf-11eb-945e-c958b1dd1774.png)

**Comment by kromar** [comment]
sorry but there is nothing i can do about this, i recommend starting in blender with the scale you need and not touching the scale master in zbrush
