### ISSUE TITLE
new vertex color node created on each import

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#29]
Every export blender makes copy of  base color attribute
![Screenshot_95](https://user-images.githubusercontent.com/22406105/59529941-02fb6780-8eeb-11e9-9a3a-8f078b08d5e4.jpg)

**Comment by kromar** [comment]
This is most likely caused by the color import that i added.
I started to work on a full system that can import the textures/material and creates the nodes required. It will replace this color import, however it will take a bit more time till its done.
I can see if i can make the current import optional and that it does not create a new base color node on every import.
