### ISSUE TITLE
The "texture image" node doesn't come out. I don't know if it's just me.

### ISSUE THREAD

**Issue by moai0924** [JoseConseco/GoB#318]
Currently, it uses Blender 3.2 and zBrush 2022. The version of 'gob' is 3.5.72.
At some point, when modeling is imported from the zBrush to the blender, the 'image texture' node does not appear in the Shader editor of the blender. I think I updated it once in the middle, but I can't find a way to go back to the past. 
The 'image texture' node itself does not appear, even though 'from texts' is selected in the import menu of the add-on option. If you choose 'from polypaint', there is an 'attribute' node, and the texture comes out well.
But I need an 'image texture' node. Because I want to take it with a program called Lumion, I need an 'image texture' node. I don't know what the problem is. Help me, T.T
![20220613_145534](https://user-images.githubusercontent.com/107386300/173288838-3430429d-88a1-421b-99db-fd82f8950c82.png)

**Comment by kromar** [comment]
make sure you have a texture map in zbrush, otherwise the node in blender is not creating a image texture node. 
![Screen Shot 06-13-22 at 10 58 PM](https://user-images.githubusercontent.com/1472884/173445369-abd1b571-00ab-4bdd-97c0-a8342fd2d7da.PNG)

i will add a ticket to create the node if no texture is found to import, this seems to make sense as default behavior.

**Comment by moai0924** [comment]
It was resolved immediately.  It was a very simple matter. Thank you. 
But I have one more problem. I'll ask you again from the top.
