### ISSUE TITLE
Export materials like polygroups for additional using

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#33]
now - 

![Imgur](https://i.imgur.com/Kb9lG8b.jpg)

FBX import -  its useful for zRemesh or Dynamesh   lowpoly boolean object with different materials 
![Imgur](https://i.imgur.com/joUtxaf.jpg)

![Imgur](https://i.imgur.com/xXhCKOb.jpg)

**Comment by kromar** [comment]
@koloved so if i understand you corectly the models are made in blender and some materials assigned to the different parts which when imported with fbx are converted into poly groups?

**Comment by koloved** [comment]
Yes  , youre right  it looks something like this

![Imgur](https://i.imgur.com/t4SvFAB.jpg)

**Comment by koloved** [comment]
[low_poly_polygroups.blend](https://github.com/JoseConseco/GoB/files/3388534/low_poly_polygroups.zip)

**Comment by kromar** [comment]
@koloved i do not know if this is possible, do you know if this works with any other application like Maya or so when sending a object with GoZ to Zbrush? Or do you have any other software you could test this?

**Comment by koloved** [comment]
I found the button in preferences menu, but its not working with obj , zbrush dont want to read mtl file

![Imgur](https://i.imgur.com/2OkVo34.jpg)

Maya isn't working with mat as poly groups too =) 

Can you make a checkbox for auto create vertex-groups from materials? (as example close to Export button)

I am trying to find addon to do this but i cant find it

**Comment by koloved** [comment]
i found this code - 

[https://blender.stackexchange.com/questions/47455/how-to-create-vertex-groups-from-materials-using-python](https://blender.stackexchange.com/questions/47455/how-to-create-vertex-groups-from-materials-using-python)

but i don't know how to use it =(

**Comment by kromar** [comment]
yeah sure i can implement such a functionality

**Comment by kromar** [comment]
@koloved there was a bug in the vertex group data that broke them sometimes during the 2.8 updates. Thanks to your request i noticed it:D
It took me some hours to trace this down and fix it and the vertex groups should again arrive as polygroups in zbrush. 
I also started to add some options in the addon preferences for the polygroups conversion but at the moment they are not working and vertex groups with the material names are created (not deleted). 
It turns out there are quite a few scenarios to cover here so that will take a bit more work. If you think there are more scenarios which can be used to create polygroups let me know so i can extend the functionality, so far i thought that materials, uv's and new with 2.8 viewport materials would be the options to add.
If you want you can give it a try and give me some feedback on how it works for you. 

https://github.com/kromar/blender_GoB/tree/feature/materials_as_polygroups

**Comment by kromar** [comment]
i removed the option for the viewport color since that is only available when a material is present so does not make sense.
the vertex groups for the material are now removed again and im working on the uv to vertex group implementation, however that turns out to be a lot more complicated than expected but i will get it done eventually^^

**Comment by nuzzar** [comment]
Hi @kromar For polygroup conversion wouldn't it be better if you use the new face map rather than vertex group? This way it would be 1:1 conversion, right?
