### ISSUE TITLE
Error Message when exporting from Blender to ZBrush

### ISSUE THREAD

**Issue by RobertShaer** [JoseConseco/GoB#330]
Hi - I'm getting the following error message when exporting and hoped someone could provide me with a fix - I hope the image gets attached correctly as I'm a total noob with GitHub! :-)

<img width="547" alt="GoBError" src="https://user-images.githubusercontent.com/108300844/176024240-b282e678-2ef7-47d6-932b-fe9d19de5031.png">

**Comment by kromar** [comment]
hi, can you try the latest version and see if you still get that issue? 

v3.5.84
https://github.com/JoseConseco/GoB/archive/refs/heads/master.zip

**Comment by RobertShaer** [comment]
> hi, can you try the latest version and see if you still get that issue?
> 
> v3.5.84 https://github.com/JoseConseco/GoB/archive/refs/heads/master.zip

Hi - thanks for getting back to me. I just tried and it looks like the same error message as the one I posted.

**Comment by kromar** [comment]
I was finally able to reproduce this and understand the issue that is causing it. It most likely is caused by a incomplete GoZ installation on zbrush and you can fix this by running the troubleshooter which should launch the goz installer. 

![image](https://user-images.githubusercontent.com/1472884/182905788-50b01426-0c1f-4c3b-a03a-ad083b19a1c7.png)
