### ISSUE TITLE
Blender Manual Page about the addon

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#35]
I made the page about the addon
Should i change something? 

https://docs.blender.org/manual/en/dev/addons/io_gob_zbrush.html

**Comment by kromar** [comment]
@koloved oh that is fantastic! 

Not all the features on the page are supported at this point
- Polyfroups from Uv’s -> propbably not going to happen since this is really easy in zbrush

these are also not working at the moment for 2.8 and might take a while.
Diffuse map
Normal map
Displacement map


there is a typo in:
`It **have** few useful import-export options:`
should be (maybe replace the it with GoB?)
GoB **has a** few useful import-export options:`

and you could use the icons of the buttons on the manual
![goz_send](https://user-images.githubusercontent.com/1472884/61414488-6283d300-a8ee-11e9-9d89-57c68ca5605d.png) ![goz_sync_disabled](https://user-images.githubusercontent.com/1472884/61414490-6283d300-a8ee-11e9-9552-c2aa569b80f0.png) ![goz_sync_enabled](https://user-images.githubusercontent.com/1472884/61414492-6283d300-a8ee-11e9-8615-4bc08c47f30a.png)

**Comment by koloved** [comment]
they asked to delete the page, I don’t understand why, as if this is not an official plugin
although in my opinion this is a very important part for the whole blender community. =(

**Comment by kromar** [comment]
@koloved to bad, however i understand the decision. imagine everybody wanted their addon on the official documentation page, it would be quite the mess:O and we are already present on the forums so i think if someone googles he will find this tool quickly.
