### ISSUE TITLE
Mesh returned mirrored or flipped

### ISSUE THREAD

**Issue by artyombon** [JoseConseco/GoB#366]
Hello!
Thanks for the great adddon!

I'm expecting one more issue. After the mesh is exported to Zbrush it gets mirrored or flipped. And when I import it back to Blender I've got this result.

![2022-08-10_22-11-27](https://user-images.githubusercontent.com/72221191/184000632-1fd31c62-63f9-43bc-86a8-76e5f0c1f4be.jpg)

I've checked face orientaton. Also I have applied all the transforms to the mesh.

**Comment by nuzzar** [comment]
I think my issue is similar to this. Notice the pivot (ignore the x position)? The pivot stays, but the object looks flip on its centre. The right one is the object GoB get when I sent to maya from zbrush. This is the expected behaviour.

![image](https://user-images.githubusercontent.com/18203407/197121503-c96ca959-8586-41b0-87fe-b37fc62254bf.png)

**Comment by kromar** [comment]
@artyombon  I changed the way meshes are flipped in the version linked (3.5.99), it would be great if you could give this a try and let me know if it still causes the same uv mirroring for you. Be aware that this is still work in progress and you most likely will encounter some issues with mesh translations.
https://github.com/kromar/blender_GoB/tree/feature/keep-transfomrmations

Note: there are new options in the export/import tabs to specify the model transformations 
![image](https://user-images.githubusercontent.com/1472884/210218609-44e4ccba-5fd7-4305-99eb-6198280372fd.png)
