### ISSUE TITLE
Make send-from-ZBrush work like official GoZ

### ISSUE THREAD

**Issue by moppius** [JoseConseco/GoB#4]
Currently the add-on has a modal timer which runs when the 2nd icon is clicked and watches for changes in the interchange folder. This works alright, but it can block some Blender functionality (such as autosave) while the modal timer is running, and is an extra action for the user to perform compared to the "official" GoZ implementations in Maya and 3dsmax.

Ideally, when the user clicks the GoZ button in ZBrush, Blender should receive focus and the script to import the GoZ files should be executed. This will bring GoB into line with the standard functionality.

I'm unsure how this can be implemented, though. Might need some sort of pipe into Blender, which is not something I've looked into before.

Other suggestions to achieve the desired result are welcome!

**Comment by kromar** [comment]
its something i noticed that blend files can not be saved while in "link" with zbrush so i wanted to see what is causing it and what the potential solutions are for this scenario. 
im not aware of the behaviour with other apps but i noticed that the auto focus would be nice when sending objects to blender. 
im not sure if blender provides such functionality since it sounds like it would be some event system that is needed. but hey there is always the possibility to implement it in blender since its open source.
@JoseConseco do you have the goz sdk from pixologic?

**Comment by JoseConseco** [comment]
fixed in 3.0.2.  Gob is using now timers, instead of modal operator.
