### ISSUE TITLE
Installing new version stopped old ones working

### ISSUE THREAD

**Issue by AckeemD** [JoseConseco/GoB#430]
So the Addon was working as intended in blender 4,

Then I decided to update to the latest version of GoB and now no versions work,

I get this message when I hit export 
![image](https://github.com/JoseConseco/GoB/assets/99124486/d2da7340-4aa4-4bba-890d-360ab8c4b0c7)

And this message when I hit manuel
![image](https://github.com/JoseConseco/GoB/assets/99124486/f9c4da86-1681-4f6c-a208-6d6f4dff4107)

**Comment by kromar** [comment]
@AckeemD since there are some big changes in the 4.0 alpha things can break on a daily basis. The current daily is not working for the addon and can not be fixed form my side. Its up to you at this point to find a combination that works.
If you need GoB i recommend using a stable version of blender where i can provide support.
