### ISSUE TITLE
specify import/export scale

### ISSUE THREAD

**Issue by xiaoilao** [JoseConseco/GoB#46]
When I export a small object to zbrush Dynamesh does not work correctly. The plugin in zbrush should change XYZ size to 2. And then returned the value XYZ size when importing.

<details>
  <summary>Images</summary>
  
  ![blender_2019-09-11_19-14-53](https://user-images.githubusercontent.com/55202067/64715094-874c8f00-d4c8-11e9-8f88-2e89b90e4cab.png)
![Dynomesh128](https://user-images.githubusercontent.com/55202067/64715104-8d427000-d4c8-11e9-85d5-3184f9a3476a.png)
![Dynomesh4096](https://user-images.githubusercontent.com/55202067/64715113-92072400-d4c8-11e9-9753-7422c711cfa8.png)
![ZBrush_2019-09-11_16-07-29](https://user-images.githubusercontent.com/55202067/64715120-95021480-d4c8-11e9-8d3e-e4b802ac77fc.png)

  
  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>

**Comment by kromar** [comment]
im aware of this, however i tried to figure this out for hours and do still not understand the logic behind zbrushes system. it seems there is not world system but every object gets its own space which has no relation to any outside software... if you have more insight please share it so i can give it another try.

**Comment by gunterrf** [comment]
I know... it took me awhile to figure it out but now its seems to work correctly for me. zBrush looks like need an object to refer the position and scale to. You have to be aware about two thing. You need an object correctly positioned and scaled(it can be a hidden subtool) and be aware about the unit size differences between Blender and zBrush. 
**1.** Download this free package from Shane Olson https://www.3dcharacterworkshop.com/. Inside the package you have a Ruler file and some cool brushes. Use the Ruler file always, otherwise your scale and position will be messed up. The ruler is 2m height. Usually I delete the sphere and I always leave the ruler on top of my subtools list and I hide it.
**2.** And the other important think that seems to me that zBrush's unit size is 100 bigger than blender's unit size, so I set my world scale unit size in Blender to 0.01 and after this two thing the scale and position is working correctly with GoB. But the problem now that the phisics, camera... etc now are messed up a litle bit because the small scale size in blender. So the ideal workflow could be that we could change the scale factor in the GoB plug in settings. That would be just wonderfull!
Sorry for my english.

**Comment by kromar** [comment]
@gunterrf @xiaoilao 

3 new ways of scaling have been added, would be great if you could try them out and let me know if you experience any issues and if something is missing.
https://github.com/kromar/blender_GoB/tree/feature/export-scale

**Manual**: lets the user define a manual scaling factor
![image](https://user-images.githubusercontent.com/1472884/85469051-7aa7ac00-b5ad-11ea-9618-16bfea131981.png)

**From Scene**: uses Blenders Scene Units to normalize scale in zbrush
![image](https://user-images.githubusercontent.com/1472884/85469080-86936e00-b5ad-11ea-85fd-33a222b74261.png)

**Experimental**: no matter the scaling in blender, your Tool in zbrush will always be scaled to specified zbrush size
![image](https://user-images.githubusercontent.com/1472884/85470465-5d73dd00-b5af-11ea-9a51-22c7375b7fd2.png)

**Comment by Tsukasa-YAMATO** [comment]
@kromar 
There is a very complicated issue with scaling between Zbrush and other software. Blender is no exception. So you may have to wait a while, but I'll definitely reply. A scale match between Blender and Zbrush is desirable for many users. I'm sure I will cooperate!

**Comment by kromar** [comment]
I am aware of the scalingscenario and have done a lot of testing on the interaction between blender and zbrush and am quite confident that the aproach is good. 
Of course i expect some anomalies that i have not yet encountered but i think we can get the logic down.
One thing i did not test yet is what happens if the unit system in blenser is changed but as far as ive seen it ahould still work since blender uses a unified scale behind what the user can see.

Take your time, i intend to work a bit now with this version so i can get a bit more experience with the current state. A lot of functionality has been added and i want to take some time to get everything stable.

**Comment by Tsukasa-YAMATO** [comment]
Bit by bit, step by step.
