### ISSUE TITLE
Can't blender polygon groups be exported to zbrush?

### ISSUE THREAD

**Issue by lazyng** [JoseConseco/GoB#468]
First of all, thank you very much to the author for making and maintaining this plugin. I was a little confused when using 4.0.2.

Can't blender polygon groups be exported to zbrush?
And I noticed that in the "Export" setting of the plugin, there is no option to export from the face map to zbrush

**Comment by thironaka0716** [comment]
I gave up to send polygroup from facemap since blender4.0 no longer supports face paint option.
Insted of facemap I use the option that import polygroup from material.
Facemap was really useful feature for GoB and if you still need it you have to use blender3.6LTS only when you use GoB.
(or protest to blender to bring back facemaps)

**Comment by kromar** [comment]
> Can't blender polygon groups be exported to zbrush?
They are not supported yet.
The changes required to work with face maps have not been implemented since they got replaced by face attributes with blender 3.6+. I have not found time to support the new attributes yet. 
There are tickets to support his so im closing this as duplicate.
