### ISSUE TITLE
Blender to zbrush crash.

### ISSUE THREAD

**Issue by KanekiK3n** [JoseConseco/GoB#51]
When I try to export my blender model to zbrush, zbrush just crashes.
I honestly have no idea how it happens, I reinstalled the addon multiple times.

**Comment by kromar** [comment]
hi @KanekiK3n this is caused if the mesh has ngons and is not triangulated on export. Zbrush will crash if it tries to load meshes that contain ngons.
Make sure you are using the latest version of GoB, this should have been fixed a long time ago. otherwise make sure you put a triangulation modifier on your mesh before sending it to zbrush.

**Comment by KanekiK3n** [comment]
Alright I'll keep an eye out for ngons!
