### ISSUE TITLE
set the level on subdivision modifier on an import object

### ISSUE THREAD

**Issue by koloved** [JoseConseco/GoB#56]
replacement (import) of the object, who has been assigned a subdivision modifier overflows memory and freezes the system
for example, how to assign a subdivision modifier to an object with 1 million polygons

PS : you could manually clean the stack of modifications before importing, but I always forget about it, then the computer freezes and has to be rebooted

**Comment by kromar** [comment]
@koloved im not sure i understand the problem, you are sending a mesh from blender which has a subdivision modifier to zbrush, sculpt there and then send a "highres" back which is inserted with the modifier stack on top of it?
could you try what happens if the modifer is disabled if the same thing happens? i might be able to add a resolution threshold where the modifier would be disabled on import. i dont like the idea so much of removing modifers.

**Comment by koloved** [comment]
@kromar 
1) export a model to zbrush (model has subdivision modifier 3) (actually it has 3 + modifier)
2) sculpt the model using dynamesh 
3) import that model without deleting object 
as i understand addon transfer modifier stack to new high poly object which freeze system 

i dont know any case when someone try to use subdivision modifier on high poly

i think  .. . an option "do nothing" and "transfer modifier stack" will be great
with additional parameter "IF imported mesh has less than ~X* polys"

**Comment by kromar** [comment]
closing this as dupplicate, please follow the progress over here: https://github.com/JoseConseco/GoB/issues/34
