### ISSUE TITLE
Gob Problem

### ISSUE THREAD

**Issue by DedasPower** [JoseConseco/GoB#59]
Hello, 

I have had this problem, but now it is consistent. So, when it normally works, I only have to click once on the import button in blender and then I can change it as many times as I want in zbrush and click the "goz" button as much as I want and it always updates in blender. Right now, I am having to click on both buttons any time I wanna make a change in zbrush. I am doing a LOT of changes in zbrush, and when it works it is amazing, but with this problem, having to go back and forth from zbrush to blender to click on each button everytime, it makes the job 2x time consuming...
If you could resolve this bug or at least tell me the reason behind, I would be very pleased.

Thank you in advanced!

**Comment by kromar** [comment]
Hi the problem is that i can not reproduce this, so i have no idea what to look for to fix this if it even is on the addon side. 
It would be great if you could try to udpate to the latest addon version and try to clean all the zbrush GoZ files, i often had issues on the zbrush goz side when something was not working rather than on the addon side. and if you find some pattern to reproduce it let me know.

**Comment by DedasPower** [comment]
Thank you! I will try to see if there is any trigger pattern.

**Comment by kromar** [comment]
@DedasPower do you still have this issue?

**Comment by valeniru** [comment]
Hi! GoB is not working for me, this is what I get:

![image](https://user-images.githubusercontent.com/95196887/143796665-e27d01ea-8ae2-450d-826d-9dd4152738fc.png
<img width="571" alt="Captura de tela 2021-11-28 205012" src="https://user-images.githubusercontent.com/95196887/143796743-b70ad637-af51-4932-800d-32c84485d921.png">
)

**Comment by kromar** [comment]
Try to run the goz installer, you can run it from the zbrush troubleshoot foldder or the gob preferences window. 
It looks like some installatiin folder is missing.
