### ISSUE TITLE
face map import is not working if the mesh contains a triangle

### ISSUE THREAD

**Issue by kromar** [JoseConseco/GoB#95]

**Comment by Tsukasa-YAMATO** [comment]
![2020-05-26_18h04_44](https://user-images.githubusercontent.com/65609416/82886592-b38a3c00-9f81-11ea-884e-12f5a95ca0f0.jpg)

When I tried it with the release version Ver.3.2.5 and Blender2.82a, the vertex group and Face Maps were correctly generated even if there were triangular polygons. Therefore, this bug indicates that there is a problem in the import implementation of Ver.3.3.4.

You can get the sample cylinder from here. Click on the cylinder icon and then press the Make PolyMesh 3D button to generate the mesh.

![2020-05-26_17h03_40](https://user-images.githubusercontent.com/65609416/82885811-97d26600-9f80-11ea-9e70-9e68b17037c8.jpg)


----------------------------------------------------------------------

https://github.com/JoseConseco/GoB/issues/87#issuecomment-633620703

> About the duplication of the maps, since in the end its supposed to be face sets and not face maps which are used in blenders sculpt mode im not sure how that will look like when the development of that feature is more mature. currently im just using the face maps since they will produce unique face selection and can be loaded into face sets. however when paining face sets in sculpt mode they are not synced with face maps and i have not found a way to currently access that data so i assume its not exposed "yet" to python.
> maybe in the future the user does not even see the maps and the cleanup question might not be relevant since they are not presented to the user.


”What are Face Sets?” Oh, it is a new feature planned to be implemented in 2.83, so I can't find it on 2.82a, hahaha. Sure, Blender might replace Face Maps with Face Sets and delete Face Maps function. In that case, you have no choice but to devise so that Face Sets can make a polygroup.

https://youtu.be/AHLEYl4-uvI

As I watched in this video, I think the legacy Face Maps for geometry control and the new Face Sets are used differently. Face Sets function is a sculpting-only feature, but Face Maps function can be used for general-purpose "face selection". Face Maps and Face Sets will not seem to integrate. At least the latest 2.83 beta hasn't been integrated yet, so it's no worried to go ahead and implement GoB using Face Maps, I guess. (Aothough I don't know what happens with Blender 2.9, it's a far distant story. :) )

Of course, it's great if Zbrush's polygroup and Blender 2.83's Face Sets are synced on GoB, but I think the first priority is to be able to go back and forth between Zbrush and Blender with the polygroup kept.

----------------------------------------------------------------------

In my case, I mainly sculpt with Zbrush and utilize polygroups to make sculpting convenient in Zbrush. On the other hand, in Blender, it is temporarily sent from Zbrush to Blender for geometry control (control of vertices, edges and faces). So I think it's nice to be able to control polygroups using Face Maps on Blender. It is good to be able to control per one face unit. (For example, assuming I can use Face Sets in sculpt mode for control of one face unit, the control of each face seems to be rather difficult. It would be easier to create a polygroup with Face Maps in edit mode or rather Zbrush's ZModeler.)

**Comment by kromar** [comment]
ah yes that helps a lot with the version test that you did! thanks a lot
i was thinking about trying that so i guess its just comparing the changes and figuring out what i did that breaks it.

**Comment by kromar** [comment]
i was able to identify the part of the code that breaks the whole thing, strangely seems to be the UV part. Ive seen some funky behaviour on the import side already so i guess its time to get to the bottom of this import issue!
Nice catch btw, thanks again for the testing

**Comment by kromar** [comment]
the issue should be fixed in this version https://github.com/kromar/blender_GoB/tree/b3_3_5

**Comment by kromar** [comment]
new version is up where facemaps should be cleaned before they are imported so they should always be valid now https://github.com/kromar/blender_GoB/tree/b3_3_6

**Comment by Tsukasa-YAMATO** [comment]
Thank you for your quick fix. I will test it as soon as possible. Please wait a day or two.

**Comment by kromar** [comment]
sure take your time

**Comment by Tsukasa-YAMATO** [comment]
I tested it and it's very good. It is well working even if there is a triangular polygon. Also FaceMaps and the vertex groups cleanup feature are working well.
Thank you for the quick actions.

If there are no problem, no bug fix and completed to the preparation for release, I would like you to release it as a stable version. Because I would like to recommend  the bug fixed version to my friends. I think many users will use GoB with peace of mind if there is a stable version which is  solved the problem of polygroups.

I'm  looking forward to the latest stable release.


--------------------------------

With GoB Ver.3.3.6, I can finally edit the polygroups on Blender and then return to Zbrush. Blender is more efficient than ZModeler on Zbrush when it comes to creating complex polygroups.

![2020-05-28_18h35_32](https://user-images.githubusercontent.com/65609416/83138115-46afa700-a125-11ea-9653-34fd85252456.jpg)


The Face Map entry that was newly created in Blender will be changed to empty entry after exporting to Zbrush and reimporting from Zbrush. But the empty entry was deleted due to the addition of this function. Instead, a meaningful "numerical entry" is generated as a polygroup. Great!

Now GoB is reborn as a very useful tool!

**Comment by kromar** [comment]
hey im glad it works for you and there are currently no issue remaining with this:D thanks to your amazing feedback it made the fixes a lot easier!

as for the stable release, there is still some work to be done on the vertex groups since their export is currently not working and needs to be rewritten as well and then there are some strange behaviors i want to track down and get resolved on the import side. after that this big change should be good for a new release! really looking forward to this as well:D
